import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Header from "~/components/Header";
import { Grid, Text } from "@nextui-org/react";

import { api } from "~/utils/api";
import GrabbableObject from "~/components/GrabbableObject";
import { useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const user = useUser()
  let notes = api.notes.getDefaultNotes.useQuery();

  if (user.user) {
    notes = api.notes.getNotes.useQuery({ userId: user.user.id });
  }

  console.log(notes.data)

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="flex h-full min-h-screen flex-col bg overflow-auto">
        {notes.data?.map(note => {
          return (
            <GrabbableObject title={note.title} body={note.content} key={note.id} />
          )
        })}
      </main>
    </>
  );
};

export default Home;
